raum_zeit/happenings/urls.py
from django.conf.urls import patterns, url
from rest_framework.urlpatterns import format_suffix_patterns
from happenings import views


locationlink_list = views.LocationLinkViewSet.as_view({
    'get': 'list',
    'post': 'create'
})




happeninglink_list = views.HappeningLinkViewSet.as_view({
    'get': 'list',
    'post': 'create'
})

performance_list = views.PerformanceViewSet.as_view({
    'get': 'list',
    'post': 'create'
})




urlpatterns = patterns('',
	url(r'^$', views.homepage_view, name='homepage'),
	url(r'^berlin$', views.CurrentHappeningCardView.as_view(), name='current_happenings_list'),
	url(r'^happenings$', views.HappeningListView.as_view(), name='happenings_list'),
	url(r'^happenings/(?P<pk>\d+)/$', views.HappeningDetailView.as_view(), name='happening_detail'),
	# url(r'^berlin/locations$', views.CurrentLocationsListView.as_view(), name='current_locations_list'),
	# url(r'^berlin/artists$', views.CurrentArtistsListView.as_view(), name='current_artist_list'),
	url(r'^signup$', views.SignUpMockView.as_view(), name='signup'),
	
	url(r'^api/locations/(?P<pk>\d+)/$', views.LocationDetail.as_view(), name='api-location-detail'),
	url(r'^api/locations/$', views.LocationList.as_view(), name='api-locations-list'),
	url(r'^api/locations/links/$', locationlink_list, name='api-locationlinks-list'),

	url(r'^api/artists/(?P<pk>\d+)/$', views.ArtistDetail.as_view(), name='api-artist-detail'),
	url(r'^api/artists/$', views.ArtistList.as_view(), name='api-artists-list'),
	url(r'^api/artists/links/$', views.ArtistLinkList.as_view(), name='api-artistlinks-list'),
	url(r'^api/artists/links/no-samples/$', views.ArtistLinkNoSamplesList.as_view(), name='api-artistlinks-no-samples'),

	url(r'^api/happenings/(?P<pk>\d+)/$', views.HappeningDetail.as_view(), name='api-happening-detail'),
	url(r'^api/happenings/$', views.HappeningList.as_view(), name='api-happenings-list'),
	url(r'^api/happenings/links/$', happeninglink_list, name='api-happeninglinks-list'),

	url(r'^api/thirdparties/(?P<pk>\d+)/$', views.ThirdPartyDetail.as_view(), name='api-thirdparty-detail'),
	url(r'^api/thirdparties/$', views.ThirdPartyList.as_view(), name='api-thirdparties-list'),

	#url(r'^api/performances/(?P<pk>\d+)/$', location_detail, name='api-location-detail'),
	url(r'^api/performances/$', performance_list, name='api-performances-list'),

	url(r'^api/$', views.api_root) # with a $ this breaks, without is hast to be the last item!
)

urlpatterns = format_suffix_patterns(urlpatterns)

raum_zeit/raum_zeit/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin



urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'raum_zeit.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('happenings.urls', namespace='happenings')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),

)

raum_zeit/happenings/models.py
import datetime
import pytz
from django.db import models
from django_extras.db.models import LatitudeField, LongitudeField
from django.core.exceptions import ValidationError
from happenings.util import now_utc

class LinksQueryMixin(object):
	""" Functionality for querysets of models that have a 'links' attribute """

	def has_link(self, url):
		""" Get an entity through a saved third_party link. """

		return self.select_related('links').filter(links__url=url).all()

	def with_links(self):
		return self.prefetch_related('links').prefetch_related('links__third_party')

#class ThirdPartyQuerySet(models.QuerySet, LinksQueryMixin):
class ThirdPartyQuerySet(models.QuerySet):
	pass

class ThirdParty(models.Model):
	""" A third party that may provide links to an entity.
		Ex: Facebook, SoundCloud, Resident Advisor
	"""
	def __str__(self):
		return self.name
	
	name = models.CharField(max_length=200, unique=True)
	url = models.URLField(unique=True)
	objects = ThirdPartyQuerySet.as_manager()

class Link(models.Model):
	""" A hyperlink relating an entity to a resource a third party
	"""
	REPR = 'REPR' 
	# link to a resource representing an entity
	# Ex.: Profil Pages, Event Pages
	SAMPLE = 'SMPL'
	# link to a resource representing an sample work of an entity
	# Ex.: SoundCloud Track link
	SEARCH = 'SRCH'
	# link to the search result of a third party for a given entity
	# Ex. Google Maps location pin

	CATEGORIES = (
		(REPR, 'Page'),
		(SAMPLE, 'Sample'),
		(SEARCH, 'Search'),
	)

	class Meta:
		abstract = True

	def __str__(self):
		return self.url

	url = models.URLField(unique=True)
	identifier = models.CharField(max_length=200, blank=True, null=True, help_text='The id used at the third party')
	is_source = models.BooleanField(default=False)
	category = models.CharField(max_length=4, choices=CATEGORIES, default=REPR)
	third_party = models.ForeignKey(ThirdParty)

class LocationLink(Link):

	location = models.ForeignKey('Location', related_name='links')

class LocationQuerySet(models.QuerySet, LinksQueryMixin):
	pass

class Location(models.Model):

	def __str__(self):
		return self.name

	name = models.CharField(max_length=200)
	address = models.CharField(max_length=200)
	lat = LatitudeField(null=True, blank=True)
	lon = LongitudeField(null=True, blank=True)
	description = models.CharField(max_length=200, default='')
	third_parties = models.ManyToManyField(ThirdParty, 
									through='LocationLink', through_fields=('location', 'third_party'))

	objects = LocationQuerySet.as_manager()

class ArtistLinkQuerySet(models.QuerySet):
	def has_link(self, url):
		return self.filter(url=url)

	def no_samples(self, third_party):
		""" Finds all links of given third party that have REPR but no SMPL links for same artist.
			
			Ex. Find all SoundCloud pages that haven't had tracks scraped from.
		"""

		repr_links = self.filter(third_party=third_party, category='REPR')
		no_smpl = repr_links.exclude(artist__links__third_party=third_party,
									 artist__links__category='SMPL')
		return no_smpl


class ArtistLink(Link):

	artist = models.ForeignKey('Artist', related_name='links')
	objects = ArtistLinkQuerySet.as_manager()

class ArtistQuerySet(models.QuerySet, LinksQueryMixin):
	
	def no_samples(self, third_party):
		""" Finds all links of given third party that have REPR but no SMPL links for same artist.
			
			Ex. Find all SoundCloud pages that haven't had tracks scraped from.
		"""
		with_repr = self.filter(links__third_party=third_party, links__category='REPR')
		without_smpl = with_repr.exclude(links__category='SMPL')
		return without_smpl


class Artist(models.Model):
	
	def __str__(self):
		return self.name

	name = models.CharField(max_length=200)
	description = models.CharField(max_length=200, default='')
	third_parties = models.ManyToManyField(ThirdParty, 
									through='ArtistLink', through_fields=('artist', 'third_party'))

	objects = ArtistQuerySet.as_manager()

	def links_with(self, category, third_party_name=None):
		
		category_links = self.links.filter(category=category)
		
		if third_party_name is not None:
			return category_links.filter(third_party__name=third_party_name)

		return category_links
	
class HappeningLink(Link):

	happening = models.ForeignKey('Happening', related_name='links')
	

class HappeningQuerySet(models.QuerySet, LinksQueryMixin):

	def in_timespan(self, after, before):
		""" Query happenings that overlap with the given timespan. 
		start < span_end = before
		stop > span_begin = after"""
    
		filtered = self.filter(start__lt=before, stop__gt=after)
		return filtered

	def with_artists(self):
		return self.prefetch_related('artists__links__third_party')

	def with_location(self):
		return self.prefetch_related('location').prefetch_related('location__links')


class Performance(models.Model):

	class Meta:
		unique_together = ('happening', 'artist')

	LIVE_MUSIC = 'LIVE' # Live music such as a band
	LIVE_DJING = 'LIDJ' # A DJ actually performing a live set
	DJING = 'DJ' 		# A DJ playing tracks, a 'non-live' set

	KINDS = ( #add gettext
		(LIVE_MUSIC, 'Live Music'),
		(LIVE_DJING, 'Live Set'),
		(DJING, 'Set')) 

	happening = models.ForeignKey('Happening', related_name='performances')
	artist = models.ForeignKey('Artist', related_name='performances')
	kind = models.CharField(max_length=4, choices=KINDS, default=DJING)
	

class Happening(models.Model):

	class Meta:
		ordering = ('start', 'stop')

	def __str__(self):
		return self.name

	name = models.CharField(max_length=200)
	start = models.DateTimeField()
	stop = models.DateTimeField()
	description = models.CharField(max_length=200, default='')

	location = models.ForeignKey(Location)
	artists = models.ManyToManyField(Artist, through=Performance)
	third_parties = models.ManyToManyField(ThirdParty, 
									through='HappeningLink', through_fields=('happening', 'third_party'))
	
	objects = HappeningQuerySet.as_manager()

	def is_active(self):
		return self.start <= now_utc() < self.stop

	def is_past(self):
		return self.stop <= now_utc()

	def is_future(self):
		return now_utc() < self.start

	def clean(self):
		if self.start > self.stop:
			raise ValidationError('Happening can not stop before it starts', code='date') # add gettext

	def duration(self):
		return self.stop - self.start

raum_zeit/happenings/views.py
import datetime

from django.views import generic
from django.http import Http404
from django.shortcuts import redirect
from rest_framework import generics
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework import viewsets
from rest_framework.exceptions import APIException, ParseError
import django_filters as filters


from happenings.serializers import LocationSerializer, ArtistSerializer, HappeningSerializer, \
    ThirdPartySerializer, LocationLinkSerializer, ArtistLinkSerializer, HappeningLinkSerializer, PerformanceSerializer
from happenings.models import Happening, HappeningLink, Location, LocationLink, Artist, ArtistLink, ThirdParty, Performance



def make_timespan(hours=12):
    now = datetime.datetime.now()
    after = datetime.datetime(now.year, now.month, now.day, now.hour)
    before = after + datetime.timedelta(hours=hours)
    return after, before

###########################
# HTML Views
###########################

def homepage_view(request):
    return redirect('happenings:current_happenings_list')

class HappeningListView(generic.ListView):
    model = Happening
    template_name = 'happenings/baseline/happening_list.html'

    def get_queryset(self):
        return Happening.objects.with_artists().with_location()


class CurrentHappeningCardView(generic.ListView):
    model = Happening
    template_name = 'happenings/baseline/happening_list.html'
    def get_queryset(self):
        after, before =  make_timespan()
        timespan_happenings = Happening.objects.in_timespan(after=after, before=before)
        return timespan_happenings.with_artists().with_location()

class SignUpMockView(generic.TemplateView):
    template_name = 'happenings/baseline/signup_mock.html'


class HappeningDetailView(generic.DetailView):
    model = Happening
    template_name = 'happenings/baseline/happening_detail.html'

###########################
# API Exceptions
###########################
# put custom exceptions here 


###########################
# API Views
###########################

@api_view(('GET',))
def api_root(request, format=None):
    return Response({
        'locations': reverse('happenings:api-locations-list', request=request, format=format),
        'artists': { 
            'list': reverse('happenings:api-artists-list', request=request, format=format),
            'queries': {
                'no-sample': reverse('happenings:api-artistlinks-no-samples', request=request, format=format),
            }
        }
    })

class LocationList(generics.ListCreateAPIView):
    """
    List all artist or create a new one.
    """
    serializer_class = LocationSerializer

    def get_queryset(self):
        queryset = Location.objects.all()
        url = self.request.query_params.get('url', None)
        if url:
            queryset = queryset.has_link(url)
            if not queryset.exists():
                raise Http404
        return queryset.with_links()

class LocationDetail(generics.RetrieveUpdateDestroyAPIView):
    """
    Retrieve, update or delete a artist instance.
    """
    queryset = Location.objects.all()
    serializer_class = LocationSerializer

class ArtistList(generics.ListCreateAPIView):
    """
    List all artist or create a new one.
    """
    serializer_class = ArtistSerializer

    def get_queryset(self):
        queryset = Artist.objects.all()
        url = self.request.query_params.get('url', None)
        if url:
            queryset = queryset.has_link(url)
            if not queryset.exists():
                raise Http404
        return queryset.with_links()

class ArtistDetail(generics.RetrieveUpdateDestroyAPIView):
    """
    Retrieve, update or delete a artist instance.
    """
    queryset = Artist.objects.all()
    serializer_class = ArtistSerializer

class HappeningList(generics.ListCreateAPIView):
    """
    List all artist or create a new one.
    """
    #queryset = Happening.objects.all()
    serializer_class = HappeningSerializer
    def get_queryset(self):
        queryset = Happening.objects.all()
        url = self.request.query_params.get('url', None)
        if url:
            queryset = queryset.has_link(url)
            if not queryset.exists():
                raise Http404
        return queryset.with_links()


class HappeningDetail(generics.RetrieveUpdateDestroyAPIView):
    """
    Retrieve, update or delete a artist instance.
    """
    queryset = Happening.objects.all()
    serializer_class = HappeningSerializer

class ThirdPartyList(generics.ListCreateAPIView):
    """
    List all thirdparties or create a new one.
    """

    serializer_class = ThirdPartySerializer

    def get_queryset(self):
        queryset = ThirdParty.objects.all()
        url = self.request.query_params.get('url', None)
        if url:
            queryset = queryset.filter(url=url)
            if not queryset.exists():
                raise Http404
        return queryset


class ThirdPartyDetail(generics.RetrieveUpdateDestroyAPIView):
    """
    Retrieve, update or delete a thirdparty instance.
    """
    queryset = ThirdParty.objects.all()
    serializer_class = ThirdPartySerializer

class LocationLinkViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list`, `create`, `retrieve`,
    `update` and `destroy` actions.


    """
    queryset = LocationLink.objects.all()
    serializer_class = LocationLinkSerializer

class ArtistLinkList(generics.ListCreateAPIView):
    """
    List all artist or create a new one.
    """
    queryset = ArtistLink.objects.all()
    serializer_class = ArtistLinkSerializer
    
# class ArtistLinkNoSamplesList(generics.ListCreateAPIView):
#     """
#     List all artist or create a new one.
#     """
#     serializer_class = ArtistLinkSerializer
#     def get_queryset(self):
#         queryset = ArtistLink.objects.all()
#         third_party = self.request.query_params.get('third_party', None)
#         if third_party:
#             queryset =  queryset.no_samples(third_party)
#             if not queryset.exists():
#                 raise Http404
#         else:
#             raise ParseError
#         return queryset
    

class ArtistLinkDetail(generics.RetrieveUpdateDestroyAPIView):
    """
    Retrieve, update or delete a artist instance.
    """
    queryset = ArtistLink.objects.all()
    serializer_class = ArtistLinkSerializer



class HappeningLinkFilter(filters.FilterSet):
    after = filters.DateTimeFilter(name='happening__start', lookup_type='gte')
    class Meta:
        model = HappeningLink
        fields = ['third_party', 'after', 'third_party__name']

class HappeningLinkViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list`, `create`, `retrieve`,
    `update` and `destroy` actions.


    """
    queryset = HappeningLink.objects.all()
    serializer_class = HappeningLinkSerializer
    filter_class = HappeningLinkFilter

class PerformanceViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list`, `create`, `retrieve`,
    `update` and `destroy` actions.


    """
    queryset = Performance.objects.all()
    serializer_class = PerformanceSerializer

raum_zeit/happenings/templates/happenings/baseline/baseline.html
{% load staticfiles %}

<!DOCTYPE HTML>
<!-- skel-baseline v2.0.2 | (c) n33 | getskel.com | MIT licensed -->
<html>
	<head>
		<title>{% block title %}{% endblock %} | dasgeht </title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<!--[if lte IE 8]><script src="{% static 'happenings/baseline/js/html5shiv.js' %}></script><![endif]-->
		<script src="{% static 'happenings/baseline/js/jquery.min.js' %}"></script>
		<script src="{% static 'happenings/baseline/js/skel.min.js' %}"></script>
		<script src="{% static 'happenings/baseline/js/skel-layers.min.js' %}"></script>

		<script src="https://w.soundcloud.com/player/api.js" ></script>
		<script>
		{% include 'happenings/baseline/js/init.js' %}
		</script>

		
		<!-- Google Analytics Opt-Out Cookie -->
		<script>
				var gaProperty = 'UA-54633103-2';
				var disableStr = 'ga-disable-' + gaProperty;
				if (document.cookie.indexOf(disableStr + '=true') > -1) {
				  window[disableStr] = true;
				}
				function gaOptout() {
				  document.cookie = disableStr + '=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/';
				  window[disableStr] = true;
				}

		</script>

		<!-- Google Analytics Anonymous Tracking-->
		<script>
			  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

			  ga('create', 'UA-54633103-2', 'auto');
			  ga('send', 'pageview');
			  ga('set', 'anonymizeIp', true);

		</script>

		<!-- <script src="{% static 'happenings/baseline/js/main.js' %}"></script>-->

		<script>

			


			$(document).ready(function() {  
				var infoBox = {

					layer: skel.plugins.layers.get('infoBox'),

					hide: function () {
						this.layer.hide();
					},

					show: function () {
						this.layer.show();
						if (streamBox.canStream) {
							this.mainButton.text('Deactivate Streaming');
						}
						else {
							this.mainButton.text('Activate Streaming');
						}
					},

					mainButton: $('#mainButton')


				};	


				var streamBox = {
					currentUrl: '',
					canStream: true,
					widget: SC.Widget('sc-widget'),
					layer: skel.plugins.layers.get('streamBox'),

					hide: function () {
							console.log('sb hi');
							this.layer.hide();},

					show: function () {
							this.layer.show();},

					toogleStreaming: function () { 
						this.canStream = !this.canStream; 
						if (this.canStream) {
							this.show();
							if (this.currentUrl != '') {
								this.loadTrack();
							}
						}
						else {
							this.hide();
						}
						return this;
					},

					loadTrack: function () {
						if (this.currentUrl) {
						this.widget.load(this.currentUrl, {'auto_play': true, 
													'show_artwork': true, 
													'download': false,
													'color': 'db5560'});
						}
					}

				};
	 
    			
    			infoBox.mainButton.click(function (event) {
    				infoBox.hide();
    				streamBox.toogleStreaming();
    			});

         		var artistItems = $('.artist-item');
				artistItems.click(function (event) {
					streamBox.currentUrl = $(this).data('soundcloud-track');
						if (streamBox.canStream) {
							infoBox.hide();
							streamBox.loadTrack();
						}
						else {
							infoBox.show();
						}
					}
				); 
			});

		</script>
		<noscript>
			<link rel="stylesheet" href="{% static 'happenings/baseline/css/skel.css' %}" />
			<link rel="stylesheet" href="{% static 'happenings/baseline/css/style.css' %}" />
			<link rel="stylesheet" href="{% static 'happenings/baseline/css/style-xlarge.css' %}" />
		</noscript>

	</head>
	<body id="top">

		<header id="header" class="skel-layers-fixed">
			<h1><a href="{% url 'happenings:homepage' %}">dasgeht </a> beta</h1>
			<nav id="nav">
			
				<ul>
				{% block nav %}
				
				{% endblock %}
				<li><a href="{% url 'happenings:signup' %}" class="button special">Sign Up</a></li>
				</ul>
			
			</nav>
		</header>

		
		{% block banner %}
		{% endblock %}

		<!-- Main -->
			<div id="main" class="container">
				{% block content %}
				{% endblock %}
			</div>

		<!-- Footer -->
			<footer id="footer">
				<div class="container">
					<div class="row double">
						<div class="6u 12u$(medium)">
							<h2>was geht?</h2>
							<p>dasgeht aims to offer quick and easy discovery of cultural events. 
							Currently we cover only Berlin and only electronic music. This might or might not change soon.
							</p>
							<p>dasgeht was designed and developed by <a href="http://hanefeld.eu">Alec Hanefeld</a>. If you have suggestions or want to talk,  <a href="mailto:/alec@hanefeld.eu">drop me a line</a></p>
						</div>
						<div class="3u 6u(medium) 12u$(small)">
							<h3>tracking</h3>
							<p>This website uses cookies. By visting this website you agree to the placement of cookies.<br/>
							This website uses Google Analytics to collect data for making your experience better. To ensure your anonymity we have removed parts of your IP address. To stop all tracking click  <a href=”javascript:gaOptout()”>here.</a>.

						</p>
						<p>Diese Seite benutzt Cookies. Mit dem Besuch der Seite stimmst Du dem zu. <br/>
						Diese Webseite benutzt Google Analytics um Besucherzahlen zu messen. Um Anonymität zu garantieren, werden Teile deiner IP entfernt. Totzdem werden Daten über dich in die USA geschickt und von Google gespeichert. Möchtest Du garnicht erfasst werden, klicke <a href=”javascript:gaOptout()”>hier.</a>.
								
						</p>
						</div>
						<div class="3u$ 6u$(medium) 12u$(small)">
							<h3>credit</h3>
							<p>All data currently comes from <a href="http://www.residentadvisor.net/">Resident Advisor</a>. Go visit their site, it has much more to offer than this one!
							</p>
							<p>All copyright of the streams belongs to the respective artists. 
							</p>
							<h3>imprint</h3>
							<ul class="alt">
								<li>Alec Hanefeld</li>
								<li>Rollbergstr. 1</li>
								<li>D-12053 Berlin</li>
								<li>alec@hanefeld.eu</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="copyright">
					&copy; Untitled. All rights reserved.
				</div>
			</footer>

	</body>
</html>

raum_zeit/happenings/templates/happenings/baseline/bottom_boxes.html
<div class="skel-layers-fixed paper" id="infoBox">
	<div class="row" id="infoBoxRow"> 
		<div class="-3u 6u$ 12u$(small)">Worried about megabytes?</div>
		<div class="-3u 6u$ 12u$(small)"><a id="mainButton" class="button alt">Deactivate Streaming</a></div>
	</div>
</div>

<div class="skel-layers-fixed" id="streamBox">
	<div class="row">
		<div class="-3u 6u$ 12u$(small)">
			<div>
				<iframe  id="sc-widget" src="https://w.soundcloud.com/player/?url=" width="200" height="80" scrolling="no" frameborder="no" ></iframe>
			</div>
		</div>
	</div>
</div>

raum_zeit/happenings/templates/happenings/baseline/happening_detail.html
{% extends 'happenings/baseline/baseline.html' %}

{% block title %}
{{ happening.location.name }} | {{ happening.name }} | nightlife music clubs 
{% endblock %}



{% block nav %}
<!--<li><a href="#top" class="button default"></a></li>-->

{% endblock %}

{% block banner %}
<!-- <div class="container">
	<div class="row">
		<div class="-4u 4u">
			<div id="bannerMenu">
				<a class="button">Go Back to Stream</a>
			</div>
		</div>
	</div>
</div> -->
{% endblock %}


{% block content %}
<div class="row">
	
	<div class="-4u 4u$ -3u(medium) 6u(medium)$ 12u$(xsmall)">
		{% include 'happenings/baseline/happening_paper.html' %}
	</div>
	
<!--</div>
<div class="row">-->
	<div class="-4u 2u 6u(small)">
		<div>
			<a class="button special" href="{% url 'happenings:signup' %}">Upload Picture</a>
		</div>
	</div>

	<div class"2u$ 6u(small)$">
		<div>
			<a class="button alt" href="{% url 'happenings:current_happenings_list' %}#{{ happening.id }}">Go Back to Stream</a>
		</div>
	</div>
</div>
{% include 'happenings/baseline/bottom_boxes.html' %}

{% endblock %}

raum_zeit/happenings/templates/happenings/baseline/happening_list.html
{% extends 'happenings/baseline/baseline.html' %}


{% block title %}
what's happening in berlin | nightlife music show clubs 
{% endblock %}


{% block nav %}
<!-- <li><a href="#top" class="button default">Happenings</a></li>
<li><a href="#content">Locations</a></li>
<li><a href="#elements">Artists</a></li> -->
{% endblock %}

{% block banner %}
<section id="banner">
	<h2>what's happening in the next 12 hours</h2>
	
</section>
{% endblock %}

{% block content %}
<div class="row uniform">
{% for happening in object_list %}
	<div class="4u{% cycle '' '' '$' %} 6u(medium) 12u$(xsmall)">
		<a id="{{happening.id}}"></a>
		{% include 'happenings/baseline/happening_paper.html' %}
	</div> 

{% endfor %}<!-- End iteration over happenigns -->
</div>
{% include 'happenings/baseline/bottom_boxes.html' %}
{% endblock %}

raum_zeit/happenings/templates/happenings/baseline/happening_paper.html
{% load humanize %}
{% load link %}
	<div class="paper">

		<!-- Location -->
		<div class="row">
			<div class="12u">
				<h2>{{ happening.location.name }}</h2>
			</div>
			<div class="10u">
				<address><p class="tiny">{{ happening.location.address }}</p></address>
			</div>
			<div class="-2u$">
				<a href="{{ happening.location.address|googlemaps }}">
					<i class="fa fa-map-marker fa-lg"></i>
				</a>
			</div>
		</div>
		<!-- Location -->
		
		<hr class="minor" />
			<!- Artists -->
		{% if happening.artists.all.exists %}
		<div class="row">
			<div class="12u$">

				<ul class="artists fa-ul" >
						{% for artist in happening.artists.all %}
							
							{% with artist.links.all|soundcloud|smpl|first as sc_sample_track %}
							{% if sc_sample_track %}
								<li class="artist-item" data-soundcloud-track="{{ sc_sample_track.url }}">
									<i class="fa fa-play-circle active"></i> {{ artist.name }} 
								</li>
							{% else %}
							<li class="artist-item">
									<i class="fa fa-play-circle-o inactive"></i> {{ artist.name }} 
								</li>
							{% endif %}
						
							{% endwith %}		
						{% endfor %}
				</ul>
			</div>
		</div>
		<hr class="minor" />
		{% endif %}
		<!-- End Artists -->

		
		<div class="row"> <!-- Happening -->
			<div class="10u">
				{% if happening.is_active %}
					<h4>{{ happening.name }}</h4>
				{% else %}
					<h4>{{ happening.name }}</h4>
				{% endif %}
			</div>
			<div class="1$">
				<a href="{% url 'happenings:happening_detail' happening.id %}"><i class="fa fa-link fa-lg"></i></a>
			</div>
			<div class="12u$ ">
				
				{% if happening.is_future %}
					<h3>starts {{ happening.start|naturaltime }}</h3>

				{% elif happening.is_active %}
					<h3 class="active">ends {{ happening.stop|naturaltime }}</h3>

				{% elif happening.is_past %}
					<h3>ended {{ happening.stop|naturaltime }}</h3>
				{% endif %}
				
			</div>
		</div>
		<!-- End Happening -->
	
		
</div> <!-- End Paper -->

raum_zeit/happenings/templates/happenings/baseline/header.html
menu.html

raum_zeit/happenings/templates/happenings/baseline/signup_mock.html
{% extends 'happenings/baseline/baseline.html' %}


{% block title %}
find out whats happening in berlin | nightlife music clubs 
{% endblock %}


{% block nav %}
<!-- <li><a href="#top" class="button default">Happenings</a></li>
<li><a href="#content">Locations</a></li>
<li><a href="#elements">Artists</a></li> -->
{% endblock %}

{% block banner %}
<section id="banner">
	<h2>Woops!</h2>
</section>
{% endblock %}

{% block content %}
<div class="row">
	<div class="-4u 4u">
		<h2>dasgeht is in early beta</h2>
		<p>Our interactive features are invite only right now.</p>
		<p>Thanks for clicken though. We have noted your interest will work even harder!</p>
	</div>
</div>
{% endblock %}